# -*- coding: utf-8 -*-
"""AI Agents Tool Calling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nU3iVD7TwjMAsUL-kUQEb0cwnE7Y6W33

### Step 1: Install Required Packages
"""

!pip install -q groq

!pip install -q pandas

"""### Step 2: Import Libraries"""

import os
import json
import pandas as pd

from groq import Groq
from google.colab import userdata

"""### Step 3: Secure API Key Access"""

GROQ_API_KEY = userdata.get("Groq_api")

if not GROQ_API_KEY:
    raise ValueError("Groq API Key not found")

print("Groq API Key Loaded Successfully")

"""### Step 4: Create Groq Client"""

client = Groq(
    api_key=GROQ_API_KEY
)

"""### Step 5: Test Groq Connection"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": "Hello Agent"
        }
    ]
)

print(response.choices[0].message.content)

"""### Step 6: Create Python Tools

#### Tool 1: Calculator
"""

def calculator(expression):

    try:
        result = eval(expression)
        return str(result)

    except Exception as e:
        return str(e)

"""#### Tool 2: Employee Search"""

EMPLOYEES = {
    "1001": "Vamshi",
    "1002": "Krishna",
    "1003": "Pavan"
}

def employee_search(emp_id):

    return EMPLOYEES.get(
        emp_id,
        "Employee Not Found"
    )

"""#### Tool 3: Invoice Search"""

INVOICES = {
    "INV001": 12000,
    "INV002": 5000,
    "INV003": 8500
}

def invoice_lookup(invoice_number):

    return INVOICES.get(
        invoice_number,
        "Invoice Not Found"
    )

"""### Step 7: Register All Tools"""

TOOLS = {
    "calculator": calculator,
    "employee_search": employee_search,
    "invoice_lookup": invoice_lookup
}

"""### Step 8: Create Agent System Prompt"""

SYSTEM_PROMPT = """
You are an AI Agent.

Available Tools:

1. calculator
2. employee_search
3. invoice_lookup

When a tool is required,
respond ONLY with JSON.

Example:

{
  "tool":"calculator",
  "input":"250*10"
}

OR

{
  "tool":"employee_search",
  "input":"1001"
}

Do not add explanation.

If no tool needed,
answer normally.
"""

"""### Step 9: Tool Selection Function"""

def decide_tool(user_query):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": user_query
            }
        ]
    )

    return response.choices[0].message.content

"""### Step 10: Execute Tool"""

def execute_tool(llm_response):

    try:

        data = json.loads(llm_response)

        tool_name = data["tool"]

        tool_input = data["input"]

        tool_function = TOOLS[tool_name]

        result = tool_function(tool_input)

        return result

    except:

        return None

"""### Step 11: Create Final Agent"""

def agent(user_query):

    llm_response = decide_tool(user_query)

    tool_result = execute_tool(llm_response)

    if tool_result:

        final_prompt = f"""
        User Query:
        {user_query}

        Tool Result:
        {tool_result}

        Generate final response.
        """

        final_response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": final_prompt
                }
            ]
        )

        return final_response.choices[0].message.content

    return llm_response

"""### Step 12: Test Agent"""

# Testing the Calculator Tool

agent("Calculate 25 * 100")

# Testing the Employees Tool

agent('how many employees with 1001')

# Testing the Invoice Tool

agent("How much Amount with invoice INV001")