# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lU4ZcXF-jDdYJN6W-icbJlGoQuY4uI-L
"""

pip install langchain-google-genai langchain_community pymupdf langchain-text-splitters faiss-cpu

import os
from google.colab import userdata
from langchain_core.prompts import ChatPromptTemplate # Prompt
from langchain_google_genai import ChatGoogleGenerativeAI # Lanchain Google GeminiAI
from langchain_core.output_parsers import StrOutputParser # Output Format
from langchain_community.document_loaders import PyMuPDFLoader # Extract the Data from PDF
from langchain_text_splitters import RecursiveCharacterTextSplitter # Chunk Data
from langchain_google_genai import GoogleGenerativeAIEmbeddings # Gemini Embedding
from langchain_community.vectorstores import FAISS # Vector DB
from langchain_core.runnables import RunnablePassthrough # for passing the user question to a retireve as well as the prompt (both)

os.environ['GOOGLE_API_KEY'] = userdata.get('RAG_API')

model_gemini = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite",
                                      temperature = 1)

# Step1 - Data Extraction

file_path = "/content/SBI Incurance.pdf"
loader = PyMuPDFLoader(file_path)
docs = loader.load()

# this is the entire data, but we will not want this entire data component to be going into a model (LLM) as that will cost more input tokens and can have hallucination
docs

# Step2 - Chunking (splitting documents into smaller components)
text_spitter = RecursiveCharacterTextSplitter(
    chunk_size = 1500,
    chunk_overlap = 300,
    add_start_index = True
)

chunks = text_spitter.split_documents(docs)

chunks

len(chunks)

# Step3 - Embedding

embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview")

# Step4 - Vector DB which is FAISS

vectordb = FAISS.from_documents(chunks,embeddings)

vectordb

# Step5 - Retrieve. All vector databases and indexes have retrieve functionality

retriever = vectordb.as_retriever(search_kwargs = {'k':5}) #retriever is now initiated

# We will pass the user question to retriever which retrieves the 5 closest chunks
# and those 5 chuncks (append page content) and use it as context in prompt

# This function just appends 5 retrieved sections and make them a single text

def format_docs(docs):
  return "\n\n".join(doc.page_content for doc in docs)

template = """

You are a SBI Insurance guy bot which only answers questions related to Health Insurance policy using the following context:

{context}

Question: {user_question}

Additional instructions:
Do not answer anything outside the context provided
If questions are not related to the context, politely respond that you are not able to answer the question and reach out to SBI Insurance support over an email.

"""

prompt = ChatPromptTemplate.from_template(template)

parser = StrOutputParser()

# Final RAG chain - retriever that gives context from user question, prompt, model, outputformat

rag_overall = ( {'context':retriever | format_docs, 'user_question':RunnablePassthrough()} | prompt | model_gemini | parser)

# Retriever will first receive the user question with 'user_question' as variable
# Then retriver gets the 5 closer chunks
# Then format_docs will append all those 5 chunks and finally save as 'context' variable

# Then prompt gets created using the "user_question" intially provided and "context" created
# Then the model and parser are kind of self explainatory

input = 'what could be cover the Health Insurance?'
response = rag_overall.invoke(input)
print(response)

input = 'what scope of cover and tell me payments it will cover in the Health Insurance?'
response = rag_overall.invoke(input)
print(response)

input = 'what could be cover the Accident Insurance Policy?'
response = rag_overall.invoke(input)
print(response)

input = 'what kind of Diseases cover in Health Insurance Policy?'
response = rag_overall.invoke(input)
print(response)

input = 'Treatment what Diseases cover in Health Insurance Policy?'
response = rag_overall.invoke(input)
print(response)